import * as Types from "./types/index.js";

export const $ = {
	ArrayBuffer: Types.$ArrayBuffer,
	ArrayBufferView: Types.$ArrayBufferView,
	BigInt64Array: Types.$BigInt64Array,
	BigUint64Array: Types.$BigUint64Array,
	Blob: Types.$Blob,
	Buffer: Types.$Buffer,
	Date: Types.$Date,
	Error: Types.$Error,
	File: Types.$File,
	Float32Array: Types.$Float32Array,
	Float64Array: Types.$Float64Array,
	Int16Array: Types.$Int16Array,
	Int32Array: Types.$Int32Array,
	Int8Array: Types.$Int8Array,
	NaN: Types.$NaN,
	RegExp: Types.$RegExp,
	Request: Types.$Request,
	Response: Types.$Response,
	URL: Types.$URL,
	Uint16Array: Types.$Uint16Array,
	Uint32Array: Types.$Uint32Array,
	Uint8Array: Types.$Uint8Array,
	Uint8ClampedArray: Types.$Uint8ClampedArray,
	any: Types.$any,
	bigint: Types.$bigint,
	boolean: Types.$boolean,
	false: Types.$false,
	falsy: Types.$falsy,
	finite: Types.$finite,
	int: Types.$int,
	never: Types.$never,
	null: Types.$null,
	nullish: Types.$nullish,
	number: Types.$number,
	object: Types.$object,
	string: Types.$string,
	symbol: Types.$symbol,
	true: Types.$true,
	type: Types.$type,
	undefined: Types.$undefined,
	unknown: Types.$unknown,

	Array: Types.$Array,
	Exact: Types.$Exact,
	Map: Types.$Map,
	Record: Types.$Record,
	Set: Types.$Set,
	Tuple: Types.$Tuple,
	enum: Types.$enum,
	instanceof: Types.$instanceof,
	literal: Types.$literal,
	maybe: Types.$maybe,
	optional: Types.$optional,
	tryinstanceof: Types.$tryinstanceof,
};
