name: main

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["**"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: npm i
      - run: npx prettier --check .

      - run: npm run build
      - run: npm run test

      - run: npm i
        working-directory: tests/
      - run: npm run test
        working-directory: tests/

      - uses: codecov/codecov-action@v3
